【开发】调整了目录结构

diff --git a/Server/configure b/Server/configure
--- a/Server/configure
+++ b/Server/configure
@@ -2260,10 +2260,145 @@ fi
 else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
+#----------------------------------------------------------------------------
+
+echo "$as_me:$LINENO: checking for event_new in -levent" >&5
+echo $ECHO_N "checking for event_new in -levent... $ECHO_C" >&6
+if test "${ac_cv_lib_event_event_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-levent  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char event_new ();
+int
+main ()
+{
+event_new ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_event_event_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_event_event_create=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_event_event_create" >&5
+echo "${ECHO_T}$ac_cv_lib_event_event_create" >&6
+if test $ac_cv_lib_event_event_create = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPTHREAD 1
+_ACEOF
+
+  LIBS="-levent $LIBS"
+
+fi
+
+if test "$ac_cv_lib_event_event_create" = yes ; then
+   CFLAGS="$CFLAGS -D_REENTRANT"
+else
+
+echo "$as_me:$LINENO: checking for event_new in -levent" >&5
+echo $ECHO_N "checking for event_new in -lpthreads... $ECHO_C" >&6
+if test "${ac_cv_lib_event_event_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-levent  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char event_new ();
+int
+main ()
+{
+event_new ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_event_event_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_event_event_create=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_event_event_create" >&5
+echo "${ECHO_T}$ac_cv_lib_event_event_create" >&6
+if test $ac_cv_lib_event_event_create = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPTHREADS 1
+_ACEOF
+
+  LIBS="-levent $LIBS"
+
+fi
+
+   if test "$ac_cv_lib_event_event_create" = yes ; then
+      CFLAGS="$CFLAGS -D_REENTRANT"
+   fi
+fi
 
 
-
-
+#----------------------------------------------------------------------------
 echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
 echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
@@ -2730,19 +2865,19 @@ _ACEOF
 fi
 
 
-#echo "$as_me:$LINENO: checking for $HOME/libglobal.a" >&5
-#echo $ECHO_N "checking for $HOME/libglobal.a... $ECHO_C" >&6
-#if test -f $HOME/libglobal.a ; then
-#	echo "$as_me:$LINENO: result: yes" >&5
-#echo "${ECHO_T}yes" >&6
-#	LIBUNP="$HOME/libglobal.a"
-#	LIBUNP_NAME=$HOME/libglobal.a
-#else
-#	echo "$as_me:$LINENO: result: no" >&5
-#echo "${ECHO_T}no" >&6
-#	LIBUNP="../libglobal.a"
-#	LIBUNP_NAME=../libglobal.a
-#fi
+echo "$as_me:$LINENO: checking for $HOME/libgame.a" >&5
+echo $ECHO_N "checking for $HOME/libgame.a... $ECHO_C" >&6
+if test -f $HOME/libgame.a ; then
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	LIBUNP="$HOME/libgame.a"
+	LIBUNP_NAME=$HOME/libgame.a
+else
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	LIBUNP="../../Common/libgame.a"
+	LIBUNP_NAME=../../Common/libgame.a
+fi
 
 #echo "$as_me:$LINENO: checking for $HOME/libunpxti.a" >&5
 #echo $ECHO_N "checking for $HOME/libunpxti.a... $ECHO_C" >&6
@@ -2991,7 +3126,6 @@ ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
 
 echo "$as_me:$LINENO: checking for egrep" >&5
 echo $ECHO_N "checking for egrep... $ECHO_C" >&6
@@ -7780,7 +7914,7 @@ LIB_OBJS=
 #LIB_OBJS="$LIB_OBJS daemon_init.o"
 #LIB_OBJS="$LIB_OBJS dg_cli.o"
 #LIB_OBJS="$LIB_OBJS dg_echo.o"
-LIB_OBJS="$LIB_OBJS error.o"
+# LIB_OBJS="$LIB_OBJS error.o"
 #LIB_OBJS="$LIB_OBJS get_ifi_info.o"
 #LIB_OBJS="$LIB_OBJS gf_time.o"
 #LIB_OBJS="$LIB_OBJS host_serv.o"
@@ -7802,8 +7936,9 @@ fi
 #fi
 #LIB_OBJS="$LIB_OBJS read_fd.o"
 #LIB_OBJS="$LIB_OBJS readline.o"
-LIB_OBJS="$LIB_OBJS readn.o"
-#LIB_OBJS="$LIB_OBJS readable_timeo.o"
+LIB_OBJS="$LIB_OBJS server_socket.o"
+LIB_OBJS="$LIB_OBJS socket.o"
+LIB_OBJS="$LIB_OBJS socket_api.o"
 #LIB_OBJS="$LIB_OBJS rtt.o"
 #LIB_OBJS="$LIB_OBJS signal.o"
 #LIB_OBJS="$LIB_OBJS signal_intr.o"
@@ -7839,7 +7974,7 @@ LIB_OBJS="$LIB_OBJS readn.o"
 #fi
 #LIB_OBJS="$LIB_OBJS wrapunix.o"
 #LIB_OBJS="$LIB_OBJS write_fd.o"
-LIB_OBJS="$LIB_OBJS writen.o"
+# LIB_OBJS="$LIB_OBJS writen.o"
 #LIB_OBJS="$LIB_OBJS writable_timeo.o"
 
 #LIBFREE_OBJS=
